/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.HostCreateStatus', null, global);
goog.exportSymbol('proto.HostCreateStatus.Code', null, global);
goog.exportSymbol('proto.Join', null, global);
goog.exportSymbol('proto.PlayerEvent', null, global);
goog.exportSymbol('proto.PlayerEvent.Op', null, global);
goog.exportSymbol('proto.PlayerScore', null, global);
goog.exportSymbol('proto.Prompt', null, global);
goog.exportSymbol('proto.Prompt.Contestant', null, global);
goog.exportSymbol('proto.PromptAnswer', null, global);
goog.exportSymbol('proto.PromptAnswer.Answer', null, global);
goog.exportSymbol('proto.Ready', null, global);
goog.exportSymbol('proto.Ready.Status', null, global);
goog.exportSymbol('proto.Resolve', null, global);
goog.exportSymbol('proto.Status', null, global);
goog.exportSymbol('proto.Status.Code', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Join = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Join, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Join.displayName = 'proto.Join';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Join.prototype.toObject = function(opt_includeInstance) {
  return proto.Join.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Join} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Join.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    playername: msg.getPlayername()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Join}
 */
proto.Join.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Join;
  return proto.Join.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Join} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Join}
 */
proto.Join.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Join} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Join.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Join.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Join.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Join} The clone.
 */
proto.Join.prototype.cloneMessage = function() {
  return /** @type {!proto.Join} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.Join.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.Join.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string playerName = 2;
 * @return {string}
 */
proto.Join.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Join.prototype.setPlayername = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Status.displayName = 'proto.Status';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Status} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    errormessage: msg.getErrormessage()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Status}
 */
proto.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Status;
  return proto.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Status}
 */
proto.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Status.Code} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Status} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Status.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Status.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Status} The clone.
 */
proto.Status.prototype.cloneMessage = function() {
  return /** @type {!proto.Status} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Code code = 1;
 * @return {!proto.Status.Code}
 */
proto.Status.prototype.getCode = function() {
  return /** @type {!proto.Status.Code} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.Status.Code} value  */
proto.Status.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string errorMessage = 2;
 * @return {string}
 */
proto.Status.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Status.prototype.setErrormessage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.Status.Code = {
  SUCCESS: 0,
  CLIENTERROR: 1,
  SERVERERROR: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.HostCreateStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.HostCreateStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.HostCreateStatus.displayName = 'proto.HostCreateStatus';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.HostCreateStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.HostCreateStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.HostCreateStatus} msg The msg instance to transform.
 * @return {!Object}
 */
proto.HostCreateStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    key: msg.getKey(),
    errormessage: msg.getErrormessage()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.HostCreateStatus}
 */
proto.HostCreateStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.HostCreateStatus;
  return proto.HostCreateStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.HostCreateStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.HostCreateStatus}
 */
proto.HostCreateStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.HostCreateStatus.Code} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.HostCreateStatus} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.HostCreateStatus.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.HostCreateStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.HostCreateStatus.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.HostCreateStatus} The clone.
 */
proto.HostCreateStatus.prototype.cloneMessage = function() {
  return /** @type {!proto.HostCreateStatus} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Code code = 1;
 * @return {!proto.HostCreateStatus.Code}
 */
proto.HostCreateStatus.prototype.getCode = function() {
  return /** @type {!proto.HostCreateStatus.Code} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.HostCreateStatus.Code} value  */
proto.HostCreateStatus.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.HostCreateStatus.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.HostCreateStatus.prototype.setKey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string errorMessage = 3;
 * @return {string}
 */
proto.HostCreateStatus.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.HostCreateStatus.prototype.setErrormessage = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.HostCreateStatus.Code = {
  SUCCESS: 0,
  CLIENTERROR: 1,
  SERVERERROR: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Ready = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Ready, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Ready.displayName = 'proto.Ready';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Ready.prototype.toObject = function(opt_includeInstance) {
  return proto.Ready.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Ready} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Ready.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: msg.getStatus()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Ready}
 */
proto.Ready.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Ready;
  return proto.Ready.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Ready} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Ready}
 */
proto.Ready.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Ready.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Ready} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Ready.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Ready.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Ready.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Ready} The clone.
 */
proto.Ready.prototype.cloneMessage = function() {
  return /** @type {!proto.Ready} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Status status = 1;
 * @return {!proto.Ready.Status}
 */
proto.Ready.prototype.getStatus = function() {
  return /** @type {!proto.Ready.Status} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.Ready.Status} value  */
proto.Ready.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.Ready.Status = {
  SUCCESS: 0,
  CLIENTERROR: 1,
  SERVERERROR: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlayerScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PlayerScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PlayerScore.displayName = 'proto.PlayerScore';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlayerScore.prototype.toObject = function(opt_includeInstance) {
  return proto.PlayerScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlayerScore} msg The msg instance to transform.
 * @return {!Object}
 */
proto.PlayerScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    scorechange: msg.getScorechange(),
    newscore: msg.getNewscore(),
    comment: msg.getComment()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlayerScore}
 */
proto.PlayerScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlayerScore;
  return proto.PlayerScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlayerScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlayerScore}
 */
proto.PlayerScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScorechange(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNewscore(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.PlayerScore} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.PlayerScore.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlayerScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.PlayerScore.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getScorechange();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getNewscore();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = this.getComment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.PlayerScore} The clone.
 */
proto.PlayerScore.prototype.cloneMessage = function() {
  return /** @type {!proto.PlayerScore} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.PlayerScore.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.PlayerScore.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 scoreChange = 2;
 * @return {number}
 */
proto.PlayerScore.prototype.getScorechange = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.PlayerScore.prototype.setScorechange = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 newScore = 3;
 * @return {number}
 */
proto.PlayerScore.prototype.getNewscore = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.PlayerScore.prototype.setNewscore = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string comment = 4;
 * @return {string}
 */
proto.PlayerScore.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.PlayerScore.prototype.setComment = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlayerEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PlayerEvent.repeatedFields_, null);
};
goog.inherits(proto.PlayerEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PlayerEvent.displayName = 'proto.PlayerEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PlayerEvent.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlayerEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.PlayerEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlayerEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.PlayerEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    op: msg.getOp(),
    playername: msg.getPlayername(),
    prompt: (f = msg.getPrompt()) && proto.Prompt.toObject(includeInstance, f),
    answer: (f = msg.getAnswer()) && proto.PromptAnswer.toObject(includeInstance, f),
    playerscoresList: jspb.Message.toObjectList(msg.getPlayerscoresList(),
    proto.PlayerScore.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlayerEvent}
 */
proto.PlayerEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlayerEvent;
  return proto.PlayerEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlayerEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlayerEvent}
 */
proto.PlayerEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PlayerEvent.Op} */ (reader.readEnum());
      msg.setOp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    case 3:
      var value = new proto.Prompt;
      reader.readMessage(value,proto.Prompt.deserializeBinaryFromReader);
      msg.setPrompt(value);
      break;
    case 4:
      var value = new proto.PromptAnswer;
      reader.readMessage(value,proto.PromptAnswer.deserializeBinaryFromReader);
      msg.setAnswer(value);
      break;
    case 5:
      var value = new proto.PlayerScore;
      reader.readMessage(value,proto.PlayerScore.deserializeBinaryFromReader);
      msg.getPlayerscoresList().push(value);
      msg.setPlayerscoresList(msg.getPlayerscoresList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.PlayerEvent} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.PlayerEvent.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlayerEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.PlayerEvent.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getOp();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = this.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getPrompt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Prompt.serializeBinaryToWriter
    );
  }
  f = this.getAnswer();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.PromptAnswer.serializeBinaryToWriter
    );
  }
  f = this.getPlayerscoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.PlayerScore.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.PlayerEvent} The clone.
 */
proto.PlayerEvent.prototype.cloneMessage = function() {
  return /** @type {!proto.PlayerEvent} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Op op = 1;
 * @return {!proto.PlayerEvent.Op}
 */
proto.PlayerEvent.prototype.getOp = function() {
  return /** @type {!proto.PlayerEvent.Op} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.PlayerEvent.Op} value  */
proto.PlayerEvent.prototype.setOp = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string playerName = 2;
 * @return {string}
 */
proto.PlayerEvent.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.PlayerEvent.prototype.setPlayername = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Prompt prompt = 3;
 * @return {proto.Prompt}
 */
proto.PlayerEvent.prototype.getPrompt = function() {
  return /** @type{proto.Prompt} */ (
    jspb.Message.getWrapperField(this, proto.Prompt, 3));
};


/** @param {proto.Prompt|undefined} value  */
proto.PlayerEvent.prototype.setPrompt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.PlayerEvent.prototype.clearPrompt = function() {
  this.setPrompt(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.PlayerEvent.prototype.hasPrompt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PromptAnswer answer = 4;
 * @return {proto.PromptAnswer}
 */
proto.PlayerEvent.prototype.getAnswer = function() {
  return /** @type{proto.PromptAnswer} */ (
    jspb.Message.getWrapperField(this, proto.PromptAnswer, 4));
};


/** @param {proto.PromptAnswer|undefined} value  */
proto.PlayerEvent.prototype.setAnswer = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.PlayerEvent.prototype.clearAnswer = function() {
  this.setAnswer(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.PlayerEvent.prototype.hasAnswer = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated PlayerScore playerScores = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.PlayerScore>}
 */
proto.PlayerEvent.prototype.getPlayerscoresList = function() {
  return /** @type{!Array.<!proto.PlayerScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PlayerScore, 5));
};


/** @param {Array.<!proto.PlayerScore>} value  */
proto.PlayerEvent.prototype.setPlayerscoresList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


proto.PlayerEvent.prototype.clearPlayerscoresList = function() {
  this.setPlayerscoresList([]);
};


/**
 * @enum {number}
 */
proto.PlayerEvent.Op = {
  NONE: 0,
  READY: 1,
  PROMPT: 2,
  ANSWERED: 3,
  RESOLVED: 4
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Prompt = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Prompt.repeatedFields_, null);
};
goog.inherits(proto.Prompt, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Prompt.displayName = 'proto.Prompt';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Prompt.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Prompt.prototype.toObject = function(opt_includeInstance) {
  return proto.Prompt.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Prompt} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Prompt.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    code: msg.getCode(),
    key: msg.getKey(),
    contestantsList: jspb.Message.toObjectList(msg.getContestantsList(),
    proto.Prompt.Contestant.toObject, includeInstance),
    optionsList: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Prompt}
 */
proto.Prompt.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Prompt;
  return proto.Prompt.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Prompt} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Prompt}
 */
proto.Prompt.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = new proto.Prompt.Contestant;
      reader.readMessage(value,proto.Prompt.Contestant.deserializeBinaryFromReader);
      msg.getContestantsList().push(value);
      msg.setContestantsList(msg.getContestantsList());
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.getOptionsList().push(value);
      msg.setOptionsList(msg.getOptionsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Prompt} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Prompt.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Prompt.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Prompt.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getContestantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.Prompt.Contestant.serializeBinaryToWriter
    );
  }
  f = this.getOptionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Prompt} The clone.
 */
proto.Prompt.prototype.cloneMessage = function() {
  return /** @type {!proto.Prompt} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Prompt.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.Prompt.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string code = 2;
 * @return {string}
 */
proto.Prompt.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Prompt.prototype.setCode = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string key = 3;
 * @return {string}
 */
proto.Prompt.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.Prompt.prototype.setKey = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated Contestant contestants = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Prompt.Contestant>}
 */
proto.Prompt.prototype.getContestantsList = function() {
  return /** @type{!Array.<!proto.Prompt.Contestant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Prompt.Contestant, 4));
};


/** @param {Array.<!proto.Prompt.Contestant>} value  */
proto.Prompt.prototype.setContestantsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.Prompt.prototype.clearContestantsList = function() {
  this.setContestantsList([]);
};


/**
 * repeated string options = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.Prompt.prototype.getOptionsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 5));
};


/** @param {Array.<string>} value  */
proto.Prompt.prototype.setOptionsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


proto.Prompt.prototype.clearOptionsList = function() {
  jspb.Message.setField(this, 5, []);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Prompt.Contestant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Prompt.Contestant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Prompt.Contestant.displayName = 'proto.Prompt.Contestant';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Prompt.Contestant.prototype.toObject = function(opt_includeInstance) {
  return proto.Prompt.Contestant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Prompt.Contestant} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Prompt.Contestant.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    thumbnail: msg.getThumbnail()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Prompt.Contestant}
 */
proto.Prompt.Contestant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Prompt.Contestant;
  return proto.Prompt.Contestant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Prompt.Contestant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Prompt.Contestant}
 */
proto.Prompt.Contestant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Prompt.Contestant} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Prompt.Contestant.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Prompt.Contestant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Prompt.Contestant.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getThumbnail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Prompt.Contestant} The clone.
 */
proto.Prompt.Contestant.prototype.cloneMessage = function() {
  return /** @type {!proto.Prompt.Contestant} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Prompt.Contestant.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.Prompt.Contestant.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string thumbnail = 2;
 * @return {string}
 */
proto.Prompt.Contestant.prototype.getThumbnail = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Prompt.Contestant.prototype.setThumbnail = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PromptAnswer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PromptAnswer.repeatedFields_, null);
};
goog.inherits(proto.PromptAnswer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PromptAnswer.displayName = 'proto.PromptAnswer';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PromptAnswer.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PromptAnswer.prototype.toObject = function(opt_includeInstance) {
  return proto.PromptAnswer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PromptAnswer} msg The msg instance to transform.
 * @return {!Object}
 */
proto.PromptAnswer.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    playername: msg.getPlayername(),
    answersList: jspb.Message.toObjectList(msg.getAnswersList(),
    proto.PromptAnswer.Answer.toObject, includeInstance),
    comment: msg.getComment()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PromptAnswer}
 */
proto.PromptAnswer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PromptAnswer;
  return proto.PromptAnswer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PromptAnswer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PromptAnswer}
 */
proto.PromptAnswer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    case 3:
      var value = new proto.PromptAnswer.Answer;
      reader.readMessage(value,proto.PromptAnswer.Answer.deserializeBinaryFromReader);
      msg.getAnswersList().push(value);
      msg.setAnswersList(msg.getAnswersList());
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.PromptAnswer} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.PromptAnswer.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PromptAnswer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.PromptAnswer.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getAnswersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.PromptAnswer.Answer.serializeBinaryToWriter
    );
  }
  f = this.getComment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.PromptAnswer} The clone.
 */
proto.PromptAnswer.prototype.cloneMessage = function() {
  return /** @type {!proto.PromptAnswer} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.PromptAnswer.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.PromptAnswer.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string playerName = 2;
 * @return {string}
 */
proto.PromptAnswer.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.PromptAnswer.prototype.setPlayername = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated Answer answers = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.PromptAnswer.Answer>}
 */
proto.PromptAnswer.prototype.getAnswersList = function() {
  return /** @type{!Array.<!proto.PromptAnswer.Answer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PromptAnswer.Answer, 3));
};


/** @param {Array.<!proto.PromptAnswer.Answer>} value  */
proto.PromptAnswer.prototype.setAnswersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.PromptAnswer.prototype.clearAnswersList = function() {
  this.setAnswersList([]);
};


/**
 * optional string comment = 4;
 * @return {string}
 */
proto.PromptAnswer.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.PromptAnswer.prototype.setComment = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PromptAnswer.Answer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PromptAnswer.Answer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PromptAnswer.Answer.displayName = 'proto.PromptAnswer.Answer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PromptAnswer.Answer.prototype.toObject = function(opt_includeInstance) {
  return proto.PromptAnswer.Answer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PromptAnswer.Answer} msg The msg instance to transform.
 * @return {!Object}
 */
proto.PromptAnswer.Answer.toObject = function(includeInstance, msg) {
  var f, obj = {
    contestant: msg.getContestant(),
    option: msg.getOption()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PromptAnswer.Answer}
 */
proto.PromptAnswer.Answer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PromptAnswer.Answer;
  return proto.PromptAnswer.Answer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PromptAnswer.Answer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PromptAnswer.Answer}
 */
proto.PromptAnswer.Answer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContestant(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.PromptAnswer.Answer} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.PromptAnswer.Answer.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PromptAnswer.Answer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.PromptAnswer.Answer.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getContestant();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getOption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.PromptAnswer.Answer} The clone.
 */
proto.PromptAnswer.Answer.prototype.cloneMessage = function() {
  return /** @type {!proto.PromptAnswer.Answer} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string contestant = 1;
 * @return {string}
 */
proto.PromptAnswer.Answer.prototype.getContestant = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.PromptAnswer.Answer.prototype.setContestant = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string option = 2;
 * @return {string}
 */
proto.PromptAnswer.Answer.prototype.getOption = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.PromptAnswer.Answer.prototype.setOption = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Resolve = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Resolve.repeatedFields_, null);
};
goog.inherits(proto.Resolve, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Resolve.displayName = 'proto.Resolve';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Resolve.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Resolve.prototype.toObject = function(opt_includeInstance) {
  return proto.Resolve.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Resolve} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Resolve.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    key: msg.getKey(),
    playerscoresList: jspb.Message.toObjectList(msg.getPlayerscoresList(),
    proto.PlayerScore.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Resolve}
 */
proto.Resolve.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Resolve;
  return proto.Resolve.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Resolve} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Resolve}
 */
proto.Resolve.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = new proto.PlayerScore;
      reader.readMessage(value,proto.PlayerScore.deserializeBinaryFromReader);
      msg.getPlayerscoresList().push(value);
      msg.setPlayerscoresList(msg.getPlayerscoresList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Resolve} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Resolve.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Resolve.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Resolve.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getPlayerscoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.PlayerScore.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Resolve} The clone.
 */
proto.Resolve.prototype.cloneMessage = function() {
  return /** @type {!proto.Resolve} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.Resolve.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.Resolve.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.Resolve.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Resolve.prototype.setKey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated PlayerScore playerScores = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.PlayerScore>}
 */
proto.Resolve.prototype.getPlayerscoresList = function() {
  return /** @type{!Array.<!proto.PlayerScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.PlayerScore, 3));
};


/** @param {Array.<!proto.PlayerScore>} value  */
proto.Resolve.prototype.setPlayerscoresList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.Resolve.prototype.clearPlayerscoresList = function() {
  this.setPlayerscoresList([]);
};


goog.object.extend(exports, proto);
